---
services:
  homeassistant:
    labels:
      - "traefik.enable=true"
      - "traefik.backend=homeassistant"
      - "traefik.frontend.rule=Host:home.ourhome.life"
      - "traefik.docker.network=traefik_proxy"
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: homeassistant
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /config:/Volume1/DockerVolumes/homeassistant
    ports:
      - 8123:8123 
    restart: unless-stopped

networks:
  traefik_proxy:
    name: traefik_proxy
    external: true